const SPKModel = function(){
    return 'SP_DGI_API_SPK'
}

const SPKDetail = function(){
    return `SP_DGI_API_SPK_DETAIL`
}

const SPK = function(){
    return `SP_DGI_API_SPK`
}


const GetSpk = function(kd_dealer,start_date, end_date){
    return `SELECT DISTINCT TOP 20 TS.NO_SPK AS idSpk,SJ.KD_DEALER, 
    TPA.NO_TRANS AS idProspect, MA.NAMA_CUSTOMER AS namaCustomer, 
    MA.NO_KTP AS noKtp, MA.ALAMAT_SURAT AS alamat, MA.KD_PROPINSI AS kodePropinsi, 
    MA.KD_KOTA AS kodeKabupaten, MA.KD_KECAMATAN AS kodeKecamatan, 
    MA.KELURAHAN AS kodeKelurahan, MA.KODE_POS AS kodePos, MA.NO_HP AS noKontak, 
    TSD.NAMA_BPKB AS namaBPKB, TSD.KTP_BPKB AS noKTPBPKB, TSD.ALAMAT_BPKB as alamatBPKB, 
    TSD.KD_PROPINSI AS kodePropinsiBPKB, TSD.KD_KABUPATEN AS kodeKabupatenBPKB, 
    TSD.KD_KECAMATAN AS kodeKecamatanBPKB, TSD.KD_KELURAHAN AS kodeKelurahanBPKB, 
    TSD.KODE_POS AS kodePosBPKB, SJ.LATITUDE, SJ.LONGITUDE, 
    MA.NO_NPWP AS NPWP, MA.NO_KK AS noKK, MK.ALAMAT_KK AS alamatKK, 
    MK.KD_PROPINSI AS kodePropinsiKK, MK.KD_KABUPATEN AS kodeKotaKK, 
    MK.KD_KECAMATAN AS kodeKecamatanKK, MK.KD_DESA AS kodeKelurahanKK, 
    MA.KODE_POS AS kodePosKK, MA.NO_FAX, MA.EMAIL, TS.KD_SALESHONDA AS idSalesPeople, 
    TES.KD_EVENT AS idEvent, TS.TGL_SPK AS tanggalPesanan, TS.STATUS_SPK AS statusSPK , 
    TS.CREATED_TIME AS createdTime, TSK.KD_TYPEMOTOR,
    datediff(DAY,FORMAT(TS.CREATED_TIME, 'yyyy/MM/dd'), FORMAT(convert(`+end_date+`,101),'yyyy/MM/dd')) AS selisihWaktu
    FROM TRANS_SPK AS TS 
    LEFT JOIN MASTER_CUSTOMER MA ON TS.KD_CUSTOMER = MA.KD_CUSTOMER AND MA.ROW_STATUS > = 0
    LEFT JOIN TRANS_SJKELUAR SJ ON TS.NO_SO = SJ.NO_REFF AND SJ.ROW_STATUS > = 0 
    LEFT JOIN MASTER_CUSTOMER_KK MK ON MA.NO_KK = MK.NO_KK AND MK.ROW_STATUS > = 0
    LEFT JOIN TRANS_PROSPECT_ACTIVITY TPA ON TS.KD_CUSTOMER = TPA.KD_CUSTOMER AND TPA.ROW_STATUS >=0
    LEFT JOIN TRANS_SPK_DETAILCUSTOMER TSD ON TS.KD_CUSTOMER = TSD.KD_CUSTOMER AND TSD.ROW_STATUS >=0
    LEFT JOIN TRANS_SPK_DETAILKENDARAAN TSK ON TS.ID = TSK.SPK_ID AND TSK.ROW_STATUS >= 0
    LEFT JOIN TRANS_SPK_SALESPROGRAM TSS ON TS.NO_SPK = TSS.NO_SPK AND TSS.ROW_STATUS > =0
    LEFT JOIN TRANS_EVENT_SALESPROGRAM TES ON TSS.KD_SALESPROGRAM = TES.KD_SALESPROGRAM AND TES.ROW_STATUS >= 0
    LEFT JOIN TRANS_FAKTURPAJAK_DETAIL TFD ON TFD.NO_TRANS = TPA.NO_TRANS AND TFD.ROW_STATUS >=0
    WHERE TS.STATUS_SPK >=4 AND SJ.KD_DEALER = '`+kd_dealer+`' AND 
    TS.CREATED_TIME >= '`+start_date+`' AND TS.CREATED_TIME <= '`+end_date+`'`
}

exports.SPK = SPK
exports.GetSpk = GetSpk
exports.SPKDetail = SPKDetail